#!/usr/bin/env python

Import('env')
Import('env_modules')

env_detour = env_modules.Clone()

# Thirdparty source files
thirdparty_dir = "#thirdparty/recastnavigation/Detour/"
thirdparty_sources = [
		"Source/DetourCommon.cpp",
		"Source/DetourAlloc.cpp",
		"Source/DetourNavMesh.cpp",
		"Source/DetourAssert.cpp",
		"Source/DetourNavMeshBuilder.cpp",
		"Source/DetourNavMeshQuery.cpp",
		"Source/DetourNode.cpp",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_detour.add_source_files(env.modules_sources, thirdparty_sources)
env_detour.Append(CPPPATH=[thirdparty_dir + "/Include"])

# Godot source files
env_detour.add_source_files(env.modules_sources, "*.cpp")

Export('env')
